name: Feature request
description: Suggest a new feature for this project.
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        We sincerely appreciate your contribution to the `willjwon/issue-template-example` project. Please use this form to propose a potential feature you think beneficial to be added.
  - type: textarea
    id: feature-request
    attributes:
      label: Feature Request
      description: Please explain us which feature you would like to propose.
      placeholder: Feature Request
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Project Version
      description: If possible, let us know the project version or commit ID you are currently working on.
  - type: textarea
    id: misc
    attributes:
      label: Miscellaneous
      description: Please provide us any other relevant information as you find necessary.
  - type: markdown
    attributes:
      value: |
        Thanks again for your time filling in this form.
